module.exports = {
    metrics: [
        {
            type: 'autogenerated',
            dirName: '.',
        },
        // {
        //     type: 'link',
        //     href: '/changelog',
        //     label: 'Changelog',
        // },
        // {
        //     type: 'link',
        //     href: '/showcase',
        //     label: 'Showcase',
        // },
        // {
        //     type: 'link',
        //     href: '/feature-requests',
        //     label: 'Feature Requests',
        // },
        // {
        //     type: 'link',
        //     label: 'Chat with us on Discord',
        //     href: 'https://discord.gg/docusaurus',
        // },
    ],
};